requirements.txt, src/ixdat/exporters/csv_exporter.py, src/ixdat/measurements.py, src/ixdat/plotters/ec_plotter.py, src/ixdat/plotters/value_plotter.py, src/ixdat/readers/biologic.py, src/ixdat/readers/ec_ms_pkl.py, src/ixdat/techniques/__init__.py, src/ixdat/techniques/deconvolution.py, src/ixdat/techniques/ec.py, src/ixdat/techniques/ms.py
Hi @kkrempl ,
Here are some updates for your [deconvolution] branch following our design workshop (DSW3), your initial comments on #6, and running all the scripts in the [Krempl2021](https://github.com/kkrempl/Dynamic-Interfacial-Reaction-Rates) repository.
The changes included just deal with small interface changes and debugging of ixdat core, not with redoing anything in the deconvolution implementation. Notably:
- The super cool but too funky `measurement.__class__ = DecoMeasurement` is no longer needed. A `TechniqueMeasurement.read()` now returns an object of class `TechniqueMeasurement` - or an inheriting class if the reader specifies it.
- `get_xxx` methods are renamed to `grab_xxx` to avoid the normal convention with "get" (see, e.g., …
=> Minor improvements after DWS3 and first #6 rev.

README.rst, development_scripts/reader_testers/test_zilien_reader.py, docs/source/technique_docs/ec_ms.rst, docs/source/tutorials.rst, src/ixdat/__init__.py, src/ixdat/exporters/ecms_exporter.py, src/ixdat/measurements.py, src/ixdat/plotters/ecms_plotter.py, src/ixdat/plotters/ms_plotter.py, src/ixdat/plotters/value_plotter.py, src/ixdat/readers/__init__.py, src/ixdat/readers/chi.py, src/ixdat/readers/ec_ms_pkl.py, src/ixdat/readers/rgasoft.py, src/ixdat/readers/zilien.py, src/ixdat/techniques/cv.py, src/ixdat/techniques/ec.py, src/ixdat/techniques/ms.py
This adds a few things to  ixdat's EC-MS analysis that proved missing or broken while preparing article repositories (https://github.com/ScottSoren/Huang2021, from which the branch gets its name) and issues #16, #17, #19, and #20:
- Molar fluxes for a calibrated molecule `mol` can be looked up using the name`"n_dot_{mol}"` (indexing for the `ValueSeries`, `grab()` for the  `t` and `n_dot` numpy arrays)
- Molar fluxes can be exported by giving a `mol_list` to the `export()` function. 
- `MSCalResults` can be dropped in for molecule names in `mol_list`s (like the `Molecule` objects of the old `EC_MS` package)
- New readers for RGA and CHI (will need to be replaced eventually - these use the old EC_MS package)
- If a background has been set by `set_bg()`, background is removed by default …
=> Additions for smoother EC-MS functionality

src/ixdat/techniques/ms.py, test.TXT
To enable calibration using very dilute gas mixtures assuming the total gas flux through the capillary is the same as for the pure carrier gas, and proportional to the concentration of the analyte. 
I modified MSInlet.gas_flux_calibration() to enable this. I am aware this is not a very pretty way since you intended to create a class for gas mixtures and then calculate their flux through the capillary in a different way, but this seemed to be the most straightforward modification for me. Happy to change it if you have better ideas.
(Since I don't have data for dilute gas mixtures available I tested it with air and the results seem plausible.)
=> Dilute gas calibration

src/ixdat/techniques/ms.py
I have added a function to calculate the effective length of a capillary given a known n_dot per pure gas.
The value is returned and put in a dict {gas:l_cap_gas_eff} such that the mean of the values can be used to calculated an averaged effective length. 
A function to update self.l_cap (float) given l_cap_eff (dict) is not empty. 
Maybe this should be directly in calc_l_cap_eff(), but I didnt want to automatically update the value self.l_cap.
=> Def calc l cap effective

README.rst, development_scripts/reader_testers/test_ixdat_csv_reader.py, development_scripts/reader_testers/test_zilien_spectrum_reader.py, docs/source/tutorials.rst, src/ixdat/exporters/sec_exporter.py, src/ixdat/exporters/spectrum_exporter.py, src/ixdat/measurements.py, src/ixdat/plotters/ecms_plotter.py, src/ixdat/plotters/ms_plotter.py, src/ixdat/plotters/sec_plotter.py, src/ixdat/readers/zilien.py, src/ixdat/spectra.py, src/ixdat/techniques/deconvolution.py, src/ixdat/techniques/ec_ms.py, src/ixdat/techniques/ms.py
Hi Kenneth, here is a small follow-up to our big merge (#30) resulting from going through the [tutorials and article repositories](https://github.com/ixdat/ixdat/blob/debug_after_big_merge/docs/source/tutorials.rst) and the reader_testers. This also resulted in a number of changes to tutorials and article repositories, which was done in each case on an **ixdat_v0p2** branch. 
Things of note in this PR
- convention established of using the string `"mol@mass"` for calibration names, or aliases for molecules of a specific isotope. Previously "_" had been used instead of "@" but it turns out this convuses `MSCalibration` which splits on arguments like `"n_dot_H2"` on `"_"` to find the molecule name. 
- A Spectrum contains a 1-D field defined only on the scanning variable, with a tstamp …
=> Debug after big merge

src/ixdat/exceptions.py, src/ixdat/tools.py, tests/unit/test_tools.py
After the discussion in #34 I now consider the deprecation decorator functionality ready for review. As an outcome of the discussion the interface has changed to use specific version, instead of time intervals, to mark hard deprecation and deletion. The interface now is:
```python
def deprecate(
last_supported_release,
update_message,
hard_deprecation_release=None,
remove_release=None,
kwarg_name=None,
):
```
which means that when applying the decorator to a class, method or function, the functionality is immediately considered soft deprecated, which means that it will issue warnings. If desired, it is possible to additionally provide `hard_deprecation_release` and `remove_release` to forewarn of when the functionality will become hard deprecated (raising exceptions) and finally be …
=> Deprecation decorators

.github/workflows/ci.yml, tasks.py
This PR aims to setup continuous integration (CI) for ixdat via [Github Actions[(https://docs.github.com/en/actions).
Github Actions is a framework for having certain actions done automatically on certain events. It is heavily used for CI, but it is by no means exclusive to that. It is e.g. possible to setup actions to e.g. make releases triggered by a tag, or to do certain things when PRs are opened, like having a bot comment if the CI fails or similar. But for now I setup just the CI. The CI checks the same items as `invoke checks` does, which now is:
- That the tests pass
- That code and tests passes flake8
- That code, tests and development scripts are black formatted
The checking of black formatted code was added in this PR along with another task for black formatting everything.
=> GitHub actions

TOOLS.rst, development_scripts/reader_testers/test_cinfdata_reader.py, development_scripts/reader_testers/test_ixdat_csv_reader.py, pyproject.toml, requirements-dev.txt, src/ixdat/constants.py, src/ixdat/db.py, src/ixdat/measurements.py, src/ixdat/readers/biologic.py, src/ixdat/readers/ec_ms_pkl.py, src/ixdat/readers/ixdat_csv.py, src/ixdat/readers/msrh_sec.py, src/ixdat/readers/reading_tools.py, src/ixdat/readers/zilien.py, src/ixdat/spectra.py, src/ixdat/techniques/analysis_tools.py, src/ixdat/techniques/deconvolution.py, src/ixdat/techniques/ec_ms.py, src/ixdat/techniques/ms.py, tasks.py, tests/functional/test_backends.py, tests/functional/test_measurements.py
I'm planning on some more improvements around tooling. This is step one. The PR contains a couple of small items:
1. I added a new `dependencies` task (alias dep) to upgrade pip, install dependencies and dev dependencies
2. I pinned the version of the dev tools that we use for checks, because it is annoying to fight over differences in this sort or tooling i.e. some code might raise a flake8 warning on one machine and not on another for the same PR due to a version bump on one of the. It is just easier to pin them and upgrade every once in a while.
3. I added a `pyproject.toml` to be able to configure `black` which will now adhere to the BDFL determined one-true line length or 89 chars
4. I updated all files with black fixes as per the new pinned version of black
=> Pin dev dependencies, extra invoke task and black style fixes

src/ixdat/readers/ixdat_csv.py
I Changed to / \[(.+)\] to search for '/ [' and make a group of what ever comes after. Not sure if '\]' is nessecary for the expression to work but I kept it for consistency
If this was meant to search for "/ (" and not make a group, then just discard this pull request and sorry.
=> regular expression in "unit":" / [(.+)]" searched for '('  '.'  '+'   ')'.

requirements-dev.txt
As per the explanation here: https://github.com/psf/black/issues/2964 there is an issue in black 22.1.0 with regards to one of its dependencies click. This PR fixes that by bumping the black dependency version to 22.3.0.
It has the tested that the version bump does not result in any format changes, so it is a trivial change.
=> Bump black version to avoid broken click dependency

NEXT_CHANGES.rst, development_scripts/append_ec_files.py, requirements-dev.txt, src/ixdat/exporters/ec_exporter.py, src/ixdat/exporters/ecms_exporter.py, src/ixdat/plotters/ec_plotter.py, src/ixdat/plotters/ms_plotter.py, src/ixdat/techniques/cv.py, src/ixdat/techniques/ec.py
This PR does the following:
- fixes `ECMSExporter`, which was broken by The Big Merge (#30)
- Has `ECMSCyclicVoltammogram.diff_with()` raise a `NotImplementedError`
- adds a deprecated `ECMSMeasurement.scan_rate` property so scripts that used this property in v0.1.x don't break 
- adds these and a few missing things to NEXT_CHANGES.rst
I think when done with the round of debugging started here, we should distribute an ixdat v0.2.1.
=> fix export bug

.github/workflows/changelog_checker.yml
This PR adds a Github Action that checks whether a PR contains changes to NEXT_CHANGES.rst. If it doesn't, it qualifies as a failed PR check, preventing the PR from begin merged. The check can be disabled for individual PR's if it is evaluated to be necessary by adding the label "skip-changelog" (which will need to be added to the label collection).
=> Add Github Action to ansure there is changelog entry in NEXT_CHANGES.rst

NEXT_CHANGES.rst, src/ixdat/techniques/ec_ms.py, src/ixdat/techniques/ms.py, tasks.py
Small edits in `ecms_calibration_curve` documentation.
Major part is an extension of `MSInlet.gas_flux_calibration()` called  `MSInlet.gas_flux_calibration_curve()` to enable multiple point calibration with either different gas concentrations or pressures as described in issue #80  I decided to just make one method with both options, but it might make more sense to separate them? let me know what you think. 
Also, I know, it's still not passing the tests, because I haven't managed to include black in my workflow (I got lost somewhere in the description in the developer doc) - will ask Kenneth to help me, but wanted to put this here already.
=> Multiple point gas flux calibration

NEXT_CHANGES.rst, src/ixdat/techniques/spectroelectrochemistry.py
Code that works now:
```
spec_1 = sec.get_spectrum(V=1.0001, interpolate=False)  # optional argument interpolate=False to choose nearest spectrum instead 
spec_2 = sec.get_spectrum(V=1.0002, interpolate=False)
print(spec_1.y == spec_2.y)  # all True! (same nearest raw spectrum)
spec_1 = sec.get_spectrum(V=1.0001)  # optional argument interpolate=False to choose nearest spectrum instead 
spec_2 = sec.get_spectrum(V=1.0002)
print(spec_1.y == spec_2.y)  # all False! (different interpolated values)
```
=> solve #141

README.rst
The link to the Development page  on readthedocs in the README is a dead link. This PR updates the link address.
=> updated dead link to development page

NEXT_CHANGES.rst, development_scripts/demo_fancy_str/demo_fancy_measurement_str.py, development_scripts/demo_fancy_str/search_for_raise_with_fstring.py, requirements-dev.txt, src/ixdat/config.py, src/ixdat/data_series.py, src/ixdat/db.py, src/ixdat/measurements.py, src/ixdat/spectra.py, src/ixdat/techniques/cv.py, src/ixdat/techniques/ms.py, src/ixdat/tools.py, tests/unit/test_data_series.py
This PR implements one possible solution (see discussion below for alternatives) for the measurement series summary PR, which is implemented by modifying the `__str__` or series and measurements.
At the most basic level, the `__str__` of data series has been changed, to show, what I hope, is a more information version for user (note, that the `__repr__` stays the same programmer oriented default and we can use that internally in places where we want that) It looks like this for a ValueSeries and TimeSeries (the part after the ":"):
```text
Voltage __repr__: ValueSeries(id=2, name='Voltage [V]')
Voltage __str__: ValueSeries: 'Voltage [V]', Span: 1.4e+00..5.4e+00V
Voltage time __repr__: TimeSeries(id=1, name='Potential time [s]')
Voltage time __str__: TimeSeries: 'Potential time [s]', Span: …
```
=> RFC: Series summary __str__

.github/workflows/ci.yml, .gitmodules, NEXT_CHANGES.rst, tests/functional/test_eclab_parser.py, tests/functional/test_zilien_reader.py
This PR is meant to enable external tests in CI. This part is already setup, but some tests are failing as mentioned here https://github.com/ixdat/ixdat/issues/158#issuecomment-1918616372. But, since https://github.com/ixdat/ixdat/pull/159 is also touching the external tests, I will wait updating this one with ignoring the tests that are still failing.
EDIT. #159 is now merged. I updated this one, so the commit of the submodule corresponds to the latest data. I also marked all the tests that fails as "skip" for now and will leave fixing those in the capable hands of @matenestor and @ScottSoren. @matenestor the skip reason includes the link to issue 158, so that are easy to find.
But this PR accomplished its main purpose, which is to make sure that externals tests are run in CI.
NOTE: I …
=> Run external tests in CI, closes #162

tests/functional/test_eclab_parser.py, tests/functional/test_zilien_reader.py
Fixes for failing tests for reading biologic files and checking dataset integration consistency. This is a patch after #134 which now creates `cycle number` and `Ns` series with `=0` suffix when they are missing in an .mpt file. (This triggered a change in Zilien code as well :smile: ).
=> Unskip biologic tests

src/ixdat/techniques/ms.py
@ScottSoren I just made the tiny change in multical to not subtract the entire measurement if no tspan_bg is passed. Decided to pull request this now since multical seems to be working fine (our issues seem to be caused by something else).
I didnt add anything to next changes. let me know if I should.
=> Fix multical to work without passing tspan_bg

CHANGES.rst, src/ixdat/__init__.py, src/ixdat/exporters/ms_exporter.py, src/ixdat/exporters/sec_exporter.py, src/ixdat/exporters/spectrum_exporter.py, src/ixdat/measurements.py, src/ixdat/readers/ixdat_csv.py
@matenestor , I spoke too soon when I said that the merge was trivial. I caught a few bugs. The CI tests passed but the external tests did not pass, and neither did the demo scripts for msrh_sec or opus_ftir. The main bug was a simple one due to incomplete removal of the redundant `delim` argument from exporter initiation. The other bug was a bit more difficult, having to do with how ixdat determines the class of the object from a file representing a spectrum that ixdat exported.
Now external tests, as well as all the demo scripts, pass! The changes are directly in CHANGES.rst, thus the failed test when CI checks NEXT_CHANGES.rst
Unfortunately, I already released 0.2.9, so this requires a quick additional release, 0.2.10. Hope to gain your quick approval!
=> --- ixdat 0.2.10 --- (bugfix)
